-- UNIZIK ATTENDANCE PWA SCHEMA

-- 1. SEMESTERS
CREATE TABLE semesters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  start_date DATE,
  end_date DATE,
  is_active BOOLEAN DEFAULT FALSE,
  is_archived BOOLEAN DEFAULT FALSE,
  user_id UUID DEFAULT auth.uid(),
  last_modified BIGINT DEFAULT (extract(epoch from now()) * 1000),
  is_deleted INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 2. STUDENTS
CREATE TABLE students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reg_number TEXT UNIQUE NOT NULL, -- PK in logic, but internal ID is BIGINT
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  user_id UUID DEFAULT auth.uid(),
  last_modified BIGINT DEFAULT (extract(epoch from now()) * 1000),
  is_deleted INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. COURSES
CREATE TABLE courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT REFERENCES semesters(id) ON DELETE CASCADE NOT NULL,
  code TEXT NOT NULL,
  title TEXT NOT NULL,
  user_id UUID DEFAULT auth.uid(),
  last_modified BIGINT DEFAULT (extract(epoch from now()) * 1000),
  is_deleted INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 4. ENROLLMENTS
CREATE TABLE enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE NOT NULL,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
  user_id UUID DEFAULT auth.uid(),
  last_modified BIGINT DEFAULT (extract(epoch from now()) * 1000),
  is_deleted INTEGER DEFAULT 0,
  UNIQUE(student_id, course_id)
);

-- 5. ATTENDANCE SESSIONS
CREATE TABLE attendance_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
  date DATE DEFAULT CURRENT_DATE NOT NULL,
  title TEXT,
  user_id UUID DEFAULT auth.uid(),
  last_modified BIGINT DEFAULT (extract(epoch from now()) * 1000),
  is_deleted INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 6. ATTENDANCE RECORDS
CREATE TABLE attendance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT REFERENCES attendance_sessions(id) ON DELETE CASCADE NOT NULL,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE NOT NULL,
  status TEXT CHECK (status IN ('present', 'absent', 'excused')) NOT NULL,
  marked_at BIGINT NOT NULL, -- Storing JS Date.now() timestamp
  user_id UUID DEFAULT auth.uid(),
  last_modified BIGINT DEFAULT (extract(epoch from now()) * 1000),
  is_deleted INTEGER DEFAULT 0,
  UNIQUE(session_id, student_id)
);

-- DISABLE RLS FOR DEVELOPMENT
ALTER TABLE semesters ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for now" ON semesters FOR ALL USING (true);
CREATE POLICY "Enable all access for now" ON students FOR ALL USING (true);
CREATE POLICY "Enable all access for now" ON courses FOR ALL USING (true);
CREATE POLICY "Enable all access for now" ON enrollments FOR ALL USING (true);
CREATE POLICY "Enable all access for now" ON attendance_sessions FOR ALL USING (true);
CREATE POLICY "Enable all access for now" ON attendance_records FOR ALL USING (true);
